# Generated by Django 5.1.2 on 2024-10-31 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_alter_subscription_course_alter_subscription_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together=set(),
        ),
    ]
