# Generated by Django 5.1.2 on 2024-11-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_alter_subscription_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="updated_at",
            field=models.DateField(
                auto_now=True, null=True, verbose_name="Дата последнего изменения"
            ),
        ),
    ]
