# Generated by Django 5.1.2 on 2024-11-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0006_lesson_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Дата последнего изменения"
            ),
        ),
    ]
